### ISSUE TITLE
Crash in FFI tests on 64-bit Arm

### ISSUE THREAD

**Issue by awilfox** [yuriy-chumak/ol#65]
During build on an Adélie Linux machine:

```
awilcox on lab-arm64-lin-1 ~ % lscpu; uname -a
Architecture:           aarch64
  CPU op-mode(s):       32-bit, 64-bit
  Byte Order:           Little Endian
CPU(s):                 4
  On-line CPU(s) list:  0-3
Vendor ID:              ARM
  Model name:           -
    Model:              0
    Thread(s) per core: 1
    Core(s) per socket: 4
    Socket(s):          1
    Stepping:           r0p0
    BogoMIPS:           38.40
    Flags:              fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ilrcpc flagm paca pacg
Linux lab-arm64-lin-1.tpcl.atwilcox.tech 6.2.0-20-generic #20-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  6 10:16:29 UTC 2023 aarch64 GNU/Linux
```

I see the following in `tmp/ffi` test output:

```
// variable arguments test (returns count of printed arguments):
int format(const char *format, ...)
{
   printf(format, ...);
}
   numbers ("%i %f %i %f" (fft-int . 42) (fft-double . 2167/50) (fft-int . 44) (fft-double . 2277/50))> ['%i %f %i %f' = {0 0.000000 3 0.000000} -> 4]  = 4
   utf-8 strings/symbols ("<%s/%s/%s/%s>" "ansi" "юнікод" 'σύμβολο "ユニコード")>
Program received signal SIGSEGV, Segmentation fault.
strlen (s=0x0) at src/string/strlen.c:17
17	src/string/strlen.c: No such file or directory.
(gdb) bt
#0  strlen (s=0x0) at src/string/strlen.c:17
#1  0x0000aaaaaaac5530 in format ()
#2  0x0000aaaaaaac5a3c in arm64_call ()
#3  0x0000aaaaaaad32a8 in OLVM_ffi ()
#4  0x0000aaaaaaaa60b4 in runtime ()
#5  0x0000aaaaaaac0c90 in OLVM_run ()
#6  0x0000aaaaaaabff58 in main ()
```

**Comment by yuriy-chumak** [comment]
Oh.
Thank you very much for the issue!

I'm checking this.

**Comment by yuriy-chumak** [comment]
Still can't reproduce with two different arm's.
Continue searching a way to find the root cause.

**Comment by awilfox** [comment]
Maybe more information about the host will help:

* GCC 13.3.0
* musl libc, 1.2.3
* Binutils 2.42, but also seen with 2.43.1 which we are testing right now
* Seen on both a Snapdragon 8cx Gen 3 and an Ampere Altra.

**Comment by yuriy-chumak** [comment]
Fixed in fd85a8f02ce65a8700abfafd3e9a58e2e222cdd1.
Fix will be included in next Ol version.

**Comment by yuriy-chumak** [comment]
Added arm64 github action runner to make autotests for linux aarch64.

**Comment by yuriy-chumak** [comment]
Fix will be included into next OL version.
